### ISSUE TITLE
mass selection for duplicates

### ISSUE THREAD

**Issue by obetz** [lfg6000/SpotifyFinder#5]
it would be useful to have an easy way to select **many** duplicates even if more than two playlists are selected in the playlist tab.

One method would be to enable "Remove Dups By Playlist" even if more than two playlists are selected in the playlist tab.

Since we can limit the  search results by the search terms below the table, a "delete all visible" button would do the same and seems to be useful, anyway.

Another improvement would be a multi-entry selection method, i.e. click first entry, shift-click last entry to select a range of consecutive lines. Don't know whether this is easy to implement.

**Comment by lfg6000** [comment]
it would be useful to have an easy way to select many duplicates 
------------------------------------------------------------------------
i started of with a "Remove Dups By Playlist" without the 2 playlist limit but found it a bit confusing when tracks from the selected playlists has duplicates across many playlists.  The idea is to make the duplicates tab as simple as possible so that the user does not end up removing tracks unwittingly and wondering what happen.   The "Remove Dups By Playlist" with the 2 playlist limit is the compromise so that there is some auto select capability when there are a large number of dups to select.

"delete all visible" button
----------------------------
this is an interesting and novel suggestion
the column filter text box is an artifact of the table.  i wonder how many users actually use the column filter text box.  i rarely use it.  

multi-entry selection method,
---------------------------------
selecting consecutive lines on the duplicates might not be so useful.   i started off with multi select on the other tabs but there were trades off with adding checkboxes.  the tables come from datatables.net, which are quite nice, but do not support rows with checkboxes with out of the box and that made multi-select much harder to sort out from a implementation point of view and i really wanted to keep the checkboxes so i let multi select go.
